export const sagaActions = {
    FETCH_USER_SAGA: "FETCH_USER_SAGA",
    FETCH_TARGET_USER_SAGA: "FETCH_TARGET_USER_SAGA",
    EDIT_USER_SAGA:"EDIT_USER_SAGA",
    DELETE_USER_SAGA:"DELETE_USER_SAGA",
    ADD_USER_SAGA: "ADD_USER_SAGA"
};
